Repository percworld/whats-cooking, pull requests merged in 2021-02, with the labels that each got.

#20 Features/html skeleton
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#42 Pantry methods
  src/Pantry.js
  src/Recipe.js
  src/RecipeRepo.js
  test/Pantry-test.js
  test/User-test.js
Labels: data model

#44 Test data refactor
  src/Pantry.js
  src/Recipe.js
  src/RecipeRepo.js
  src/User.js
  test-data/ingredient-test-data.js
  test-data/recipe-test-data.js
  test-data/user-test-data.js
  test/Pantry-test.js
Labels: data model, feedback

#47 Test Refactor
  data/recipes.js
  src/Pantry.js
  src/Recipe.js
  src/RecipeRepo.js
  src/scripts.js
  test-data/user-test-data.js
  test/Pantry-test.js
Labels: data model

#48 Features/check pantry
  src/index.html
  src/scripts.js
  src/styles.css
Labels: DOM

#51 Fix/refactor
  src/index.html
  src/scripts.js
  src/styles.css
Labels: Problems

#52 Test helper functions
  test/Pantry-test.js
Labels: data model
